Given a bank customer, build a neural network-based classifier that can determine whether
they will leave or not in the next 6 months.
Dataset Description: The case study is from an open-source dataset from Kaggle.
The dataset contains 10,000 sample points with 14 distinct features such as
CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance, etc.
Link to the Kaggle project:
https://www.kaggle.com/barelydedicated/bank-customer-churn-modeling
Perform following steps:
1. Read the dataset.
2. Distinguish the feature and target set and divide the data set into training and test sets.
3. Normalize the train and test data.
4. Initialize and build the model. Identify the points of improvement and implement the same.
5. Print the accuracy score and confusion matrix (5 points).

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df = df.drop(['RowNumber','Surname','CustomerId'], axis = 1)

In [6]:
states = pd.get_dummies(df['Geography'],drop_first = True)
gender = pd.get_dummies(df['Gender'],drop_first = True)
df = df.drop(['Geography','Gender'], axis = 1)

In [7]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1
3,699,39,1,0.00,2,0,0,93826.63,0
4,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0
9996,516,35,10,57369.61,1,1,1,101699.77,0
9997,709,36,7,0.00,1,0,1,42085.58,1
9998,772,42,3,75075.31,2,1,0,92888.52,1
9999,792,28,4,130142.79,1,1,0,38190.78,0

In [8]:
df = pd.concat([df,gender,states], axis = 1)
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Male,Germany,Spain
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,1,0
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [9]:
x = df.drop('Exited', axis = 1)
y = df['Exited']

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30)

In [11]:
x_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Male,Germany,Spain
9723,526,32,7,125540.05,1,0,0,86786.41,1,0,0
8394,692,69,10,154953.94,1,1,1,70849.47,1,0,0
4623,709,24,3,110949.41,1,1,1,168515.61,0,0,0
6393,593,41,4,119703.10,2,1,1,109783.29,0,1,0
5484,748,45,2,119852.01,1,0,0,73853.94,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
1087,498,31,10,0.00,2,1,0,13892.57,0,0,0
6271,747,49,6,202904.64,1,1,1,17298.72,1,0,0
5691,744,44,5,120654.68,1,1,0,82290.81,1,0,1
3252,641,31,10,155978.17,1,1,0,91510.71,1,0,0
9127,630,39,10,105473.74,1,0,0,58854.88,1,0,1

In [12]:
y_train

9723    0
8394    0
4623    0
6393    0
5484    1
       ..
1087    0
6271    1
5691    0
3252    0
9127    1
Name: Exited, Length: 7000, dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [25]:
import keras
from keras.models import Sequential
from keras.layers import Dense #To create hidden layers

classifier = Sequential()
classifier.add(Dense(activation = "relu", input_dim = 11,units = 6, kernel_initializer = "uniform"))
classifier.add(Dense(activation = "relu", units = 6, kernel_initializer = "uniform"))   #Adding second hidden layers
classifier.add(Dense(activation = "sigmoid", units = 1,kernel_initializer = "uniform"))  #Final neuron will be having siigmoid function

classifier.compile(optimizer="adam", loss = 'binary_crossentropy', metrics = ['accuracy']) #To compile the Artificial Neural Network. Ussed Binary crossentropy as we just have only two output
classifier.summary() #3 layers created. 6 neurons in 1st,6neurons in 2nd layer and 1 neuron in last

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 6)                 72

 dense_4 (Dense)             (None, 6)                 42

 dense_5 (Dense)             (None, 1)                 7

=================================================================
Total params: 121 (484.00 Byte)
Trainable params: 121 (484.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
classifier.fit(x_train,y_train,batch_size=10,epochs=50) #Fitting the ANN to training dataset

Epoch 1/50
700/700 [==============================] - 4s 4ms/step - loss: 0.4941 - accuracy: 0.7929
Epoch 2/50
700/700 [==============================] - 2s 3ms/step - loss: 0.4274 - accuracy: 0.7937
Epoch 3/50
700/700 [==============================] - 1s 2ms/step - loss: 0.4210 - accuracy: 0.8086
Epoch 4/50
700/700 [==============================] - 1s 2ms/step - loss: 0.4161 - accuracy: 0.8280
Epoch 5/50
700/700 [==============================] - 1s 2ms/step - loss: 0.4109 - accuracy: 0.8297
Epoch 6/50
700/700 [==============================] - 2s 3ms/step - loss: 0.4072 - accuracy: 0.8346
Epoch 7/50
700/700 [==============================] - 2s 3ms/step - loss: 0.4038 - accuracy: 0.8340
Epoch 8/50
700/700 [==============================] - 3s 4ms/step - loss: 0.4024 - accuracy: 0.8351
Epoch 9/50
700/700 [==============================] - 2s 2ms/step - loss: 0.4005 - accuracy: 0.8347
Epoch 10/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3996 - accuracy: 0.8356
Epoch 11/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3990 - accuracy: 0.8357
Epoch 12/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3977 - accuracy: 0.8359
Epoch 13/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3967 - accuracy: 0.8369
Epoch 14/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3968 - accuracy: 0.8356
Epoch 15/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3961 - accuracy: 0.8363
Epoch 16/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3960 - accuracy: 0.8356
Epoch 17/50
700/700 [==============================] - 2s 2ms/step - loss: 0.3950 - accuracy: 0.8376
Epoch 18/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3951 - accuracy: 0.8377
Epoch 19/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3950 - accuracy: 0.8376
Epoch 20/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3942 - accuracy: 0.8363
Epoch 21/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3941 - accuracy: 0.8381
Epoch 22/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3941 - accuracy: 0.8357
Epoch 23/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3933 - accuracy: 0.8359
Epoch 24/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3940 - accuracy: 0.8371
Epoch 25/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3940 - accuracy: 0.8374
Epoch 26/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3937 - accuracy: 0.8366
Epoch 27/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3938 - accuracy: 0.8363
Epoch 28/50
700/700 [==============================] - 2s 4ms/step - loss: 0.3936 - accuracy: 0.8366
Epoch 29/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3934 - accuracy: 0.8353
Epoch 30/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3934 - accuracy: 0.8360
Epoch 31/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3936 - accuracy: 0.8359
Epoch 32/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3933 - accuracy: 0.8380
Epoch 33/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3933 - accuracy: 0.8366
Epoch 34/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3931 - accuracy: 0.8367
Epoch 35/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3932 - accuracy: 0.8354
Epoch 36/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3931 - accuracy: 0.8370
Epoch 37/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3929 - accuracy: 0.8369
Epoch 38/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3929 - accuracy: 0.8390
Epoch 39/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3925 - accuracy: 0.8379
Epoch 40/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3933 - accuracy: 0.8377
Epoch 41/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3928 - accuracy: 0.8357
Epoch 42/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3926 - accuracy: 0.8387
Epoch 43/50
700/700 [==============================] - 2s 2ms/step - loss: 0.3928 - accuracy: 0.8376
Epoch 44/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3925 - accuracy: 0.8389
Epoch 45/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3926 - accuracy: 0.8383
Epoch 46/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3928 - accuracy: 0.8386
Epoch 47/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3919 - accuracy: 0.8394
Epoch 48/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3922 - accuracy: 0.8377
Epoch 49/50
700/700 [==============================] - 1s 2ms/step - loss: 0.3924 - accuracy: 0.8393
Epoch 50/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3926 - accuracy: 0.8390

In [27]:
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

94/94 [==============================] - 0s 1ms/step

In [28]:
from sklearn import metrics

In [29]:
metrics.accuracy_score(y_test, y_pred)

0.8376666666666667

In [30]:
metrics.confusion_matrix(y_test, y_pred)

array([[2329,   78],
       [ 409,  184]])